services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: bridge_db
    environment:
      POSTGRES_DB: bridge_discussion
      POSTGRES_USER: bridge_user
      POSTGRES_PASSWORD: bridge_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bridge_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bridge_backend
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql://bridge_user:bridge_password@db:5432/bridge_discussion
      - PORT=3001
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - bridge_network
    command: >
      sh -c "echo '--- Generating Prisma client ---' &&
             npm run db:generate &&
             echo '--- Building application ---' &&
             npm run build &&
             echo '--- Deploying database migrations ---' &&
             npm run db:deploy &&
             echo '--- Seeding database ---' &&
             npm run db:seed &&
             echo '--- Starting backend server ---' &&
             npm run start"

  # Prisma Studio UI
  db-ui:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bridge_db_ui
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://bridge_user:bridge_password@db:5432/bridge_discussion
    depends_on:
      - db
    networks:
      - bridge_network
    command: >
      sh -c "npm run db:generate && npm run db:studio"

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: bridge_frontend
    env_file:
      - ./.env
    networks:
      - bridge_network
    depends_on:
      - backend # Ensure backend is ready for API calls during frontend build

  # Caddy Reverse Proxy
  caddy:
    image: caddy:2-alpine
    container_name: bridge_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - frontend
      - backend
    networks:
      - bridge_network

volumes:
  postgres_data:
  caddy_data:

networks:
  bridge_network:
    driver: bridge
