services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: bridge_db
    environment:
      POSTGRES_DB: bridge_discussion
      POSTGRES_USER: bridge_user
      POSTGRES_PASSWORD: bridge_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bridge_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bridge_backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://bridge_user:bridge_password@db:5432/bridge_discussion
      - PORT=3001
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:5173}
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - bridge_network
    command: npm run dev

  # Frontend (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: bridge_frontend
    environment:
      - VITE_API_URL=http://localhost:3001/api
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - bridge_network
    command: npm run dev

volumes:
  postgres_data:

networks:
  bridge_network:
    driver: bridge